start_index = 0
end_index = 300
save_file_path = "mlps_d"
batch_size = 48
dataset_path = "/home/gijsv/projects/emulating-3dpdr/3dpdr_dataset_8192.h5"
learning_rate = 0.0011269044339
weight_scale = 1.0
weight_truncation = 1000.0
shuffle_every_n_epochs = 1
weight_decay = 0.0001274459152
input_features_file = "configs/input_features_v1.toml"
enc_dec_depth = 1
enc_dec_width = 592
aux_features = true
minimal_timeseries_length = 32
training_batch_subsampling = 1.0
model = "latent"
depth = 3
width = 592
bottleneck = 37
final_activation = "tanh"

[train_test_val_split]
train = 0.7
validate = 0.15
test = 0.15

[[learning_schemes]]
timeseries_fraction = 0.33
epochs = 50
lr_scheduler = "sgdr"
warmup_epochs = 2
learning_rate = 0.0011269044339

[[learning_schemes]]
timeseries_fraction = 0.67
epochs = 50
lr_scheduler = "sgdr"
warmup_epochs = 2
learning_rate = 0.0011269044339

[[learning_schemes]]
timeseries_fraction = 1.0
epochs = 50
lr_scheduler = "sgdr"
warmup_epochs = 2
learning_rate = 0.0011269044339
