start_index = 0
end_index = 300
save_file_path = "mlps_2"
batch_size = 128
dataset_path = "data/zenodo/v1/3dpdr_dataset_8192.h5"
learning_rate = 0.003
weight_scale = 0.2
weight_truncation = 10.0
shuffle_every_n_epochs = 1
weight_decay = 0.0
enc_dec_depth = 2
enc_dec_width = 512
aux_features = true
minimal_timeseries_length = 32
training_batch_subsampling = 1.0
input_features_file = "configs/input_features_v1.toml"
model = "latent"
depth = 2
width = 512
bottleneck = 32
final_activation = "tanh"

[train_test_val_split]
train = 0.7
validate = 0.15
test = 0.15

[[learning_schemes]]
timeseries_fraction = 0.33
epochs = 50
lr_scheduler = "sgdr"
warmup_epochs = 2
learning_rate = 0.003

[[learning_schemes]]
timeseries_fraction = 0.67
epochs = 50
lr_scheduler = "sgdr"
warmup_epochs = 2
learning_rate = 0.003

[[learning_schemes]]
timeseries_fraction = 1.0
epochs = 50
lr_scheduler = "sgdr"
warmup_epochs = 2
learning_rate = 0.003
