[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neuralpdr"
version = "2024.9.6"
authors = [
  {name = "Gijs Vermariën", email = "vermarien@strw.leidenuniv.nl"}
]
maintainers = [
  {name = "Gijs Vermariën", email = "vermarien@strw.leidenuniv.nl"}
]
description = "A 3dpdr emulator"
readme = "README.rst"
license = {file = "LICENSE.txt"}
keywords = ["Astronomy", "Astrochemistry", "Surrogate model", "NeuralODE"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
requires-python = ">=3.10,<3.14" # for ray
dependencies = [
    "PyYAML",
    "chex==0.1.86",
    "diffrax==0.6.0",
    "equinox==0.11.4",
    "h5py",
    "jax==0.4.31",
    "jaxlib==0.4.31",
    "jaxtyping==0.2.33",
    "joblib",
    "matplotlib",
    # "neptune",
    "numpy==1.26.4",
    "opt-einsum",
    "optax==0.2.3",
    "orbax",
    "pandas",
    "pydantic",
    "pytest",
    "ray",
    "tomlkit",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["tests/test_*.py"]
addopts = ["--import-mode=importlib", "-ra"]
markers = ["integration: integration tests"]
filterwarnings = [
    "ignore:jsonschema.RefResolver is deprecated:DeprecationWarning",
]
