"iv": "visual_extinction"
"data":
- "CH3OH"
- "CS"
- "CO+"
- "H2CO"
- "HCO"
- "C2"
- "HCN"
- "NH"
- "HCO+"
- "CN"
- "O2"
- "CH"
- "H2O"
- "C"
- "CO"
- "O"
- "H2"
- "H"
- "e-"
"aux":
- "visual_extinction"
- "tgas"
- "tdust"
- "density"
- "radfield"
- "zeta"
